src/main/java/com/algaworks/pedidovenda/model/Pedido.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.inject.Inject;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

import com.algaworks.pedidovenda.service.CadastroPedidoService;
import com.algaworks.pedidovenda.service.ParcelamentoService;
import com.algaworks.pedidovenda.util.jpa.Transactional;

@Entity
@Table(name = "pedido")
public class Pedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Date dataCriacao;
	private String observacao;
	private BigDecimal valorDesconto = BigDecimal.ZERO;
	private BigDecimal valorTotal = BigDecimal.ZERO;
	private StatusPedido status = StatusPedido.ORCAMENTO;
	private FormaPagamento formaPagamento;
	private Usuario vendedor;
	private Cliente cliente;
	private Integer repetir;
	private List<ItemPedido> itens = new ArrayList<>();
	private List<Parcelamento> parcelamentos = new ArrayList<>();
	private Date dataQuita;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}

	@Transient
	public boolean isExistente() {
		return !isNovo();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Column(columnDefinition = "text")
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	
	@Column(name = "repetir", nullable = true)
	public Integer getRepetir() {
		return repetir;
	}

	public void setRepetir(Integer repetir) {
		this.repetir = repetir;
	}

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	public List<Parcelamento> getParcelamentos() {
		return parcelamentos;
	}

	public void setParcelamentos(List<Parcelamento> parcelamentos) {
		this.parcelamentos = parcelamentos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", nullable = true)
	public Date getDataQuita() {
		return dataQuita;
	}

	public void setDataQuita(Date dataQuita) {
		this.dataQuita = dataQuita;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorSubtotal() {
		BigDecimal total = BigDecimal.ZERO;
		// somar itens do pedido
		for (ItemPedido item : this.getItens()) {// Soma os pedidos adicionados
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		return total;
	}

	@Transient
	public Integer getParcelas() {
		return this.getRepetir();
	}

	public void recalcularValorTotal() {
		BigDecimal total = BigDecimal.ZERO;

		total = total.subtract(this.getValorDesconto());

		// somar itens do pedido
		for (ItemPedido item : this.getItens()) {// Soma os pedidos adicionados
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		this.setValorTotal(total);
	}

	// Adiciona item vazio na capa de pedido dentro do item
	public void adicionarItemVazio() {
		if (this.isOrcamento()) { // Se for orçamento adiciona
			Produto produto = new Produto();

			ItemPedido item = new ItemPedido();
			item.setProduto(produto);
			item.setPedido(this);

			this.getItens().add(0, item);// Adiciona o item na posição zero,
											// sempre
		}

	}

	@Transient
	// Nao é mapeamento JPA (Get)
	public boolean isOrcamento() {
		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	public void removerItemVazio() {
		ItemPedido primeiroItem = this.getItens().get(0);

		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(0);
		}

	}

	@Transient
	public Integer getNumParc() {
		return this.getRepetir();
	}

	@Transient
	public boolean isValorTotalNegativo() {
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}

	@Transient
	public boolean isPromissoria() {
		return FormaPagamento.PROMISSORIA.equals(this.getFormaPagamento());
	}

	@Transient
	public boolean isParcelavel() {
		return this.isPromissoria() || this.isCartaoCredito();
	}

	@Transient
	public boolean isCartaoCredito() {
		return FormaPagamento.CARTAO_CREDITO.equals(this.getFormaPagamento());
	}

	@Transient
	public boolean isNaoEmissivel() {
		return !this.isEmissivel();
	}

	@Transient
	public boolean isEmissivel() {
		return this.isExistente() && this.isOrcamento();
	}

	@Transient
	public boolean isNaoCancelavel() {
		return !isCancelavel();

	}

	@Transient
	public boolean isCancelavel() {
		return this.isExistente() && !this.isCancelado();
	}

	@Transient
	public boolean isQuitado() {
		return this.getDataQuita() != null;
	}

	@Transient
	public boolean isQuitadobotao() {
		return this.isOrcamento() || this.isQuitado();
	}

	@Transient
	private boolean isCancelado() {
		return StatusPedido.CANCELADO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoAlteravel() {
		return !isAlteravel();
	}

	@Transient
	private boolean isAlteravel() {
		return this.isOrcamento();
	}

	@Transient
	private boolean isCredito() {
		return FormaPagamento.CARTAO_CREDITO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoEnviavelPorEmail() {
		return this.isNovo() || this.isCancelado();
	}

	@Transient
	public boolean isNulo() {
		return this.getItens() != null;
	}

}

src/main/java/com/algaworks/pedidovenda/controller/CadastroPedidoBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.enterprise.event.Observes;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.lang3.StringUtils;
import org.primefaces.event.CellEditEvent;

import com.algaworks.pedidovenda.model.Cliente;
import com.algaworks.pedidovenda.model.FormaPagamento;
import com.algaworks.pedidovenda.model.ItemPedido;
import com.algaworks.pedidovenda.model.Pagamento;
import com.algaworks.pedidovenda.model.Parcelamento;
import com.algaworks.pedidovenda.model.Pedido;
import com.algaworks.pedidovenda.model.Produto;
import com.algaworks.pedidovenda.model.Usuario;
import com.algaworks.pedidovenda.repository.Clientes;
import com.algaworks.pedidovenda.repository.Produtos;
import com.algaworks.pedidovenda.repository.Usuarios;
import com.algaworks.pedidovenda.service.CadastroPedidoService;
import com.algaworks.pedidovenda.service.NegocioException;
import com.algaworks.pedidovenda.service.ParcelamentoService;
import com.algaworks.pedidovenda.util.DateFormat;
import com.algaworks.pedidovenda.util.jsf.FacesUtil;
import com.algaworks.pedidovenda.validation.SKU;

@Named
@ViewScoped
public class CadastroPedidoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Parcelamento parcelamento;

	@Inject
	private Usuarios usuarios;

	@Inject
	private Clientes clientes;

	@Inject
	private Produtos produtos;

	@Inject
	private CadastroPedidoService cadastroPedidoService;

	private ArrayList<Parcelamento> parcelasPedido;

	private String sku;

	@Produces
	@PedidoEdicao
	private Pedido pedido;

	private List<Usuario> vendedores;

	private Produto produtoLinhaEditavel;

	@Inject
	private ParcelamentoService cadastroParcelamentoService;

	public void pedidoAlterado(@Observes PedidoAlteradoEvent event) {
		this.pedido = event.getPedido(); // O pedido recebe o pedidoevent da
											// classe PedidoAlteradoEvent
	}

	public CadastroPedidoBean() {
		limpar();
	}

	public void inicializar() {
		if (FacesUtil.isNotPostBack()) {
			this.vendedores = this.usuarios.vendedores();

			this.pedido.adicionarItemVazio();

			this.recalcularPedido();
		}
	}

	private void limpar() {
		pedido = new Pedido();
		parcelamento = new Parcelamento();
	}

	public void salvar() throws ParseException {
		this.pedido.removerItemVazio();
		try {
			this.pedido = this.cadastroPedidoService.salvar(this.pedido);
			FacesUtil.addInfoMessage("Pedido salvo com sucesso!");
		} finally {
			this.pedido.adicionarItemVazio();
		}
	}

	public void recalcularPedido() {
		if (this.pedido != null) {
			this.pedido.recalcularValorTotal();
		}
	}

	public void carregarProdutoPorSku() {
		if (StringUtils.isNotEmpty(this.sku)) {
			this.produtoLinhaEditavel = this.produtos.porSku(this.sku);
			this.carregarProdutoLinhaEditavel();
		}
	}

	public void carregarProdutoLinhaEditavel() {
		ItemPedido item = this.pedido.getItens().get(0);

		if (this.produtoLinhaEditavel != null) {
			if (this.existeItemComProduto(this.produtoLinhaEditavel)) {
				FacesUtil
						.addErrorMessage("Já existe um item no pedido com o produto informado.");
			} else {
				item.setProduto(this.produtoLinhaEditavel);
				item.setValorUnitario(this.produtoLinhaEditavel
						.getValorUnitario());
				item.setValorCusto(this.produtoLinhaEditavel.getValorcusto());
				this.pedido.adicionarItemVazio();
				this.produtoLinhaEditavel = null;
				this.sku = null;

				this.pedido.recalcularValorTotal();
			}
		}
	}

	private boolean existeItemComProduto(Produto produto) {
		boolean existeItem = false;
		// Intera em todos os itens do pedido
		for (ItemPedido item : this.getPedido().getItens()) {
			// se o produto que recebemos como parametro for igual ao produto do
			// item
			if (produto.equals(item.getProduto())) {
				existeItem = true; // true
				break;// e para
			}
		}

		return existeItem;
	}

	public ArrayList<Parcelamento> Parcelamento(BigDecimal valorTotal,
			Integer parcelamentos) throws ParseException {

		ArrayList<Parcelamento> parcelamentoList = new ArrayList<>();
		Calendar cFirst = Calendar.getInstance();
		SimpleDateFormat dataFormadata = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss.S");
		cFirst.setTime(this.parcelamento.getDate());
		double valorParc = 0.0;
		valorParc = valorTotal.doubleValue() / parcelamentos.doubleValue();

		for (int i = 1; i <= parcelamentos; i++) {
			Parcelamento parcela = new Parcelamento();
			parcela.setNum_parc(i);
			String cFirstString = dataFormadata.format(cFirst.getTime());
			Date Date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S")
					.parse(cFirstString);
			parcela.setDate(Date);
			parcela.setValores(new BigDecimal(valorParc).setScale(2,
					RoundingMode.CEILING));
			if (this.pedido.isCartaoCredito()) {
				parcela.setPagamento(Pagamento.PAGA);
			}
			parcela.setPedido(this.pedido);
			parcelamentoList.add(parcela);
			cFirst.add(Calendar.MONTH, 1);

		}

		return parcelamentoList;
	}

	public void calculaParcelas() throws ParseException {

		if (this.pedido.isParcelavel() && this.pedido.isNulo()) {
			this.parcelasPedido = new ArrayList<Parcelamento>();
			this.pedido.getParcelamentos().clear();
			this.parcelasPedido = this.Parcelamento(
					this.pedido.getValorSubtotal(), this.pedido.getParcelas());
			this.pedido.getParcelamentos().addAll(this.parcelasPedido);
		} else {
			FacesUtil
					.addErrorMessage("Somente para Promissória e Cartão de Crédito."
							+ " Pedido também deve possuir pelo menos um item");

		}

	}

	public List<Produto> completarProduto(String nome) {
		return this.produtos.porNome(nome);
	}

	public void atualizarQuantidade(ItemPedido item, int linha) {
		if (item.getQuantidade() < 1) {
			// Nao posso remover a primeira linha
			if (linha == 0) {
				item.setQuantidade(1);
			} else {
				this.getPedido().getItens().remove(linha);
			}
		}

		this.pedido.recalcularValorTotal();
	}

	public void atualizarParcela(Parcelamento parcelamento, int linha) {
		Integer i = Integer.valueOf(parcelamento.getValores().toString());
		Integer auxiliar = i;
		// Logica setar Pago ou em Débito
		if (i < 1) {
			parcelamento.setPagamento(Pagamento.PAGA);
		}
		if (i > 1) {
			parcelamento.setPagamento(Pagamento.PARCIAL);
		}

	}

	public void onCellEdit(CellEditEvent event) {
		Object oldValue = event.getOldValue();
		Object newValue = event.getNewValue();

		if (newValue != null && !newValue.equals(oldValue)) {
			FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO,
					"Status da parcela foi alterado", "Old: " + oldValue
							+ ", New:" + newValue);
			FacesContext.getCurrentInstance().addMessage(null, msg);
		}
	}

	public void quitarPedido() {
		this.pedido.setDataQuita(new Date());
		List<Parcelamento> parcelamentosEditar = this.pedido.getParcelamentos();

		for (Parcelamento parcelamento : parcelamentosEditar) {
			if(parcelamento.isEmDebito()){
				parcelamento.setPagamento(Pagamento.QUITADO);	
			}
			
		}
	}

	public FormaPagamento[] getFormasPagamento() {
		return FormaPagamento.values();
	}

	public Pagamento[] getEstadoPagamento() {
		return Pagamento.values();
	}

	public List<Cliente> completarCliente(String nome) {
		return this.clientes.porNome(nome);
	}

	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public List<Usuario> getVendedores() {
		return vendedores;
	}

	public boolean isEditando() {
		return this.pedido.getId() != null;
	}

	public Produto getProdutoLinhaEditavel() {
		return produtoLinhaEditavel;
	}

	public void setProdutoLinhaEditavel(Produto produtoLinhaEditavel) {
		this.produtoLinhaEditavel = produtoLinhaEditavel;
	}

	@SKU
	public String getSku() {
		return sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public Parcelamento getParcelamento() {
		return parcelamento;
	}

	public void setParcelamento(Parcelamento parcelamento) {
		this.parcelamento = parcelamento;
	}

	public ArrayList<Parcelamento> getParcelasPedido() {
		return parcelasPedido;
	}

	public void setParcelasPedido(ArrayList<Parcelamento> parcelasPedido) {
		this.parcelasPedido = parcelasPedido;
	}

}

src/main/webapp/pedidos/CadastroPedido.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">

	<f:metadata>
		<o:viewParam name="pedido" value="#{cadastroPedidoBean.pedido}" />
		<f:event listener="#{cadastroPedidoBean.inicializar}"
			type="preRenderView" />
	</f:metadata>

	<ui:define name="titulo">#{cadastroPedidoBean.editando ? "Edição de pedido" : "Novo Pedido"}</ui:define>

	<ui:define name="corpo">
		<h:form id="frmCadastro">
			<h1>#{cadastroPedidoBean.editando ? "Edição de pedido" : "Novo
				Pedido"}</h1>

			<p:messages autoUpdate="true" closable="true" />

			<ui:include src="/WEB-INF/template/pedidos/BotoesPedido.xhtml" />

			<ui:include src="/WEB-INF/template/pedidos/CapaPedido.xhtml" />

			<p:tabView style="margin-top: 20px">
				<p:tab title="Itens">
					<ui:include src="/WEB-INF/template/pedidos/ItensPedido.xhtml" />
				</p:tab>
				<p:tab title="Parcelamento">
					<ui:include src="/WEB-INF/template/pedidos/ParcelamentoPedido.xhtml" />
				</p:tab>
				<p:tab title="Observação">
					<ui:include src="/WEB-INF/template/pedidos/ObservacaoPedido.xhtml" />
				</p:tab>
			</p:tabView>

		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pedidos/PesquisaPedidos.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Pesquisa de pedidos</ui:define>

	<ui:define name="corpo">
		<h:form id="frmPesquisa">
			<h1>Pesquisa de pedidos</h1>

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar"
						action="#{pesquisaPedidosBean.pesquisar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/pedidos/CadastroPedido" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:panelGrid columns="2" id="painel"
				style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo">
				<p:outputLabel value="Número" />
				<h:panelGroup>
					<p:inputText size="10"
						value="#{pesquisaPedidosBean.filtro.numeroDe}" />
	    			a
	    			<p:inputText size="10"
						value="#{pesquisaPedidosBean.filtro.numeroAte}" />
				</h:panelGroup>

				<p:outputLabel value="Data de criação" />
				<h:panelGroup>
					<p:calendar size="10" pattern="dd/MM/yyyy"
						value="#{pesquisaPedidosBean.filtro.dataCriacaoDe}" />
	    			a
	    			<p:calendar size="10" pattern="dd/MM/yyyy"
						value="#{pesquisaPedidosBean.filtro.dataCriacaoAte}" />
				</h:panelGroup>

				<p:outputLabel value="Vendedor" />
				<p:inputText size="40"
					value="#{pesquisaPedidosBean.filtro.nomeVendedor}" />

				<p:outputLabel value="Cliente" />
				<p:inputText size="40"
					value="#{pesquisaPedidosBean.filtro.nomeCliente}" />

				<p:outputLabel value="Status" />
				<p:selectManyCheckbox value="#{pesquisaPedidosBean.filtro.statuses}">
					<f:selectItems value="#{pesquisaPedidosBean.statuses}" var="status"
						itemValue="#{status}" itemLabel="#{status.descricao}" />
				</p:selectManyCheckbox>
			</p:panelGrid>

			<p:dataTable id="pedidosTable"
				value="#{pesquisaPedidosBean.pedidosFiltrados}" var="pedido"
				style="margin-top: 20px" emptyMessage="Nenhum pedido encontrado."
				rows="20" paginator="true" paginatorAlwaysVisible="false"
				paginatorPosition="bottom">
				<p:column headerText="Número"
					style="text-align: center; width: 100px">
					<h:outputText value="#{pedido.id}" />
				</p:column>
				<p:column headerText="Cliente">
					<h:outputText value="#{pedido.cliente.nome}" />
				</p:column>
				<p:column headerText="Vendedor">
					<h:outputText value="#{pedido.vendedor.nome}" />
				</p:column>
				<p:column headerText="Data de criação"
					style="text-align: center; width: 140px">
					<h:outputText value="#{pedido.dataCriacao}">
						<f:convertDateTime pattern="dd/MM/yyyy" />
					</h:outputText>
				</p:column>
				<p:column headerText="Valor total"
					style="text-align: right; width: 120px">
					<h:outputText value="#{pedido.valorTotal}">
						<f:convertNumber type="currency" />
					</h:outputText>
				</p:column>
				<p:column headerText="Status" style="width: 100px">
					<h:outputText value="#{pedido.status.descricao}" />
				</p:column>
				<p:column style="text-align: center; width: 50px">

					<p:commandButton icon="ui-icon-trash" title="Excluir"
						oncomplete="confirmacaoExclusao.show()" process="@this"
						update=":frmPesquisa:confirmacaoExclusaoDialog" rendered="#{pedido.naoCancelavel}">
						<!-- Atribui o produto a ser excluido em uma variavel no Bean -->
						<f:setPropertyActionListener value="#{pedido}"
							target="#{pesquisaPedidosBean.pedidoSelecionado}" />
					</p:commandButton>
					<p:button icon="ui-icon-pencil" title="Editar"
						outcome="/pedidos/CadastroPedido">
						<f:param name="pedido" value="#{pedido.id}" />
					</p:button>
				</p:column>
			</p:dataTable>

			<p:confirmDialog header="Exclusão de pedido"
				message="Tem certeza que deseja excluir o pedido?"
				widgetVar="confirmacaoExclusao" id="confirmacaoExclusaoDialog">
				<p:button value="Não"
					onclick="confirmacaoExclusao.hide(); return false;" />
				<p:commandButton value="Sim"
					oncomplete="confirmacaoExclusao.hide();"
					action="#{pesquisaPedidosBean.excluir}" process="@this"
					update=":frmPesquisa:pedidosTable" />
			</p:confirmDialog>

		</h:form>
	</ui:define>
</ui:composition>