src/main/java/com/algaworks/pedidovenda/model/Cliente.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.br.CPF;

@Entity //Entidade JPA
@Table(name ="cliente")
public class Cliente implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private String nome;
	private String email;
	private String documentoReceitaFederal;
	private TipoPessoa tipo;
	private String telefone;
	private List<Endereco> enderecos = new ArrayList<>();
	
	 
	@Id
	@GeneratedValue //AutoIncremento
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@NotBlank
	@Size(max = 80)
	@Column(nullable = false, length = 100)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Email
	@NotBlank
	@Column(nullable = false, length = 100)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@CPF
	@Column(name = "doc_receita_federal", nullable = false, length = 14)
	public String getDocumentoReceitaFederal() {
		return documentoReceitaFederal;
	}

	public void setDocumentoReceitaFederal(String documentoReceitaFederal) {
		this.documentoReceitaFederal = documentoReceitaFederal;
	}
	
	
	@Column(name = "telefone", nullable = true)
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 12)
	public TipoPessoa getTipo() {
		return tipo;
	}

	public void setTipo(TipoPessoa tipo) {
		this.tipo = tipo;
	}
	
	@NotNull
	@OneToMany(mappedBy = "cliente", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	public List<Endereco> getEnderecos() {
		return enderecos;
	}

	public void setEnderecos(List<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente other = (Cliente) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/algaworks/pedidovenda/controller/CadastroClienteBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.pedidovenda.model.Cliente;
import com.algaworks.pedidovenda.model.Endereco;
import com.algaworks.pedidovenda.model.TipoPessoa;
import com.algaworks.pedidovenda.repository.Enderecos;
import com.algaworks.pedidovenda.service.CadastroClienteService;
import com.algaworks.pedidovenda.util.jsf.FacesUtil;


@Named
@ViewScoped
public class CadastroClienteBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private Cliente cliente;
	
	private Endereco endereco;
	
	private TipoPessoa tipopessoa;
	



	public void inicializar() {
		
		
			//endereco = new Endereco();
		
		
	}
	
	@Inject
	CadastroClienteService cadastroClienteService;
	
	
	
	public TipoPessoa getTipopessoa() {
		return tipopessoa;
	}


	public void setTipopessoa(TipoPessoa tipopessoa) {
		this.tipopessoa = tipopessoa;
	}


	

	public Endereco getEndereco() {
		return endereco;
	}


	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}


	public Cliente getCliente() {
		return cliente;
	}


	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}


	public CadastroClienteBean() {
		cliente = new Cliente();
		endereco = new Endereco();
		}
	

	public void salvar() {
		this.cliente = cadastroClienteService.salvar(this.cliente);
		FacesUtil.addInfoMessage("Cliente salvo com sucesso!");
		cliente = new Cliente();


	}

	public TipoPessoa[] getTipoCliente(){
        return TipoPessoa.values();
    } 
	
	public boolean isEditando() {
		return this.cliente.getId() != null;
	}
	
	public void adicionarEndereco() {
		this.endereco.setCliente(this.cliente);
		this.cliente.getEnderecos().add(this.endereco);
		FacesUtil.addInfoMessage("Endereco adicionado.");
	
	}
	
	public void removerEndereco(){
		this.cliente.getEnderecos().remove(this.endereco);
		//this.cliente = cadastroClienteService.salvar(this.cliente);
	}
	
	public void editarEndereco() {
		this.cliente.getEnderecos()
		.set(this.cliente.getEnderecos().indexOf(endereco), endereco);
		}
	

}

src/main/java/com/algaworks/pedidovenda/controller/PesquisaClientesBean.java
package com.algaworks.pedidovenda.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
















import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.algaworks.pedidovenda.model.Cliente;
import com.algaworks.pedidovenda.model.Produto;
import com.algaworks.pedidovenda.model.Usuario;
import com.algaworks.pedidovenda.repository.Clientes;
import com.algaworks.pedidovenda.repository.Produtos;
import com.algaworks.pedidovenda.repository.Usuarios;
import com.algaworks.pedidovenda.repository.filter.ClienteFilter;
import com.algaworks.pedidovenda.repository.filter.ProdutoFilter;
import com.algaworks.pedidovenda.repository.filter.UsuarioFilter;
import com.algaworks.pedidovenda.util.jsf.FacesUtil;

@Named
@ViewScoped
public class PesquisaClientesBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private ClienteFilter filtro;


	@Inject
	private Clientes clientes;

	private List<Cliente> clientesFiltrados;
	
	private Cliente clienteSelecionado;
	
	
	
	public ClienteFilter getFiltro() {
		return filtro;
	}



	public void setFiltro(ClienteFilter filtro) {
		this.filtro = filtro;
	}







	public List<Cliente> getClientesFiltrados() {
		return clientesFiltrados;
	}



	public void setClientesFiltrados(List<Cliente> clientesFiltrados) {
		this.clientesFiltrados = clientesFiltrados;
	}



	public Cliente getClienteSelecionado() {
		return clienteSelecionado;
	}



	public void setClienteSelecionado(Cliente clienteSelecionado) {
		this.clienteSelecionado = clienteSelecionado;
	}



	public void pesquisar(){
		clientesFiltrados = clientes.filtrados(filtro);
	}
	
	
	
	public PesquisaClientesBean() {
		filtro = new ClienteFilter();
	}
	
	public void excluir(){
		//Cliente atribuido no xhtml
		clientes.remover(clienteSelecionado);
		clientesFiltrados.remove(clienteSelecionado);
		
		FacesUtil.addInfoMessage("Usuario " + clienteSelecionado.getNome() +" excluido com sucesso.");
	}



	public Clientes getClientes() {
		return clientes;
	}



	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}
	

	
}

src/main/webapp/clientes/CadastroCliente.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">





	<ui:define name="titulo">#{cadastroClienteBean.editando ? "Edição de Cliente" : "Novo Cliente"}</ui:define>

	<ui:define name="corpo">


		<f:metadata>
			<o:viewParam name="cliente" value="#{cadastroClienteBean.cliente}" />
			<f:event listener="#{cadastroClienteBean.inicializar}"
				type="preRenderView" />
		</f:metadata>
		<h:form id="frmCadastro">



			<h1>#{cadastroClienteBean.editando ? "Edição de Cliente" : "Novo
				Cliente"}</h1>

			<p:messages autoUpdate="true" closable="true" />



			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:button value="Novo" outcome="/clientes/CadastroCliente" />
					<p:commandButton value="Salvar" id="botaoSalvar"
						action="#{cadastroClienteBean.salvar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Pesquisa" outcome="/clientes/PesquisaClientes" />
				</p:toolbarGroup>
			</p:toolbar>


			<p:panelGrid columns="2" id="painel"
				style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo">


				<p:outputLabel value="Nome" for="nome" />
				<p:inputText id="nome" size="60" maxlength="80"
					value="#{cadastroClienteBean.cliente.nome}" />

				<p:outputLabel for="tipoPessoa" value="Tipo" />

				<h:panelGroup>
					<p:selectOneRadio id="tipoPessoa"
						value="#{cadastroClienteBean.cliente.tipo}"
						converter="omnifaces.GenericEnumConverter">
						<f:selectItems value="#{cadastroClienteBean.tipoCliente}"
							var="tipopessoa" itemValue="#{tipopessoa}" />

					</p:selectOneRadio>
				</h:panelGroup>

				<p:outputLabel value="CNPJ" for="cnpj" />
				<p:inputMask id="cnpj" size="15" maxlength="20"
					mask="999.999.999-99"
					value="#{cadastroClienteBean.cliente.documentoReceitaFederal}" />

				<p:outputLabel value="Email" for="email" />
				<p:inputText id="email" size="60" maxlength="80"
					value="#{cadastroClienteBean.cliente.email}" />

				<p:outputLabel value="Telefone Celular" for="telefone" />
				<p:inputMask id="telefone" size="15" maxlength="20"
					mask="(99)99999-9999"
					value="#{cadastroClienteBean.cliente.telefone}" />

			</p:panelGrid>



			<p:commandButton value="Adicionar Endereço" style="margin-top: 20px"
				oncomplete="inclusaoEnderecoDlg.show();" process="@this" />






			<p:dialog header="Inclusão de endereço"
				widgetVar="inclusaoEnderecoDlg" id="enderecoDialogo" modal="true"
				resizable="false">
				<h:panelGroup id="pnlEndereco">

					<p:panelGrid columns="2" columnClasses="rotulo, campo">
						<p:outputLabel value="Logradouro" for="logradouro" />
						<p:inputText id="logradouro" size="60" maxlength="80"
							value="#{cadastroClienteBean.endereco.logradouro}" />

						<p:outputLabel value="Numero" for="numero" />
						<p:inputText id="numero" size="8" maxlength="80"
							value="#{cadastroClienteBean.endereco.numero}" />

						<p:outputLabel value="Complemento" for="complemento" />
						<p:inputText id="complemento" size="30" maxlength="80"
							value="#{cadastroClienteBean.endereco.complemento}" />

						<p:outputLabel value="CEP" for="cep" />
						<p:inputText id="cep" size="20" maxlength="80"
							value="#{cadastroClienteBean.endereco.cep}" />

						<p:outputLabel value="Cidade" for="cidade" />
						<p:inputText id="cidade"
							value="#{cadastroClienteBean.endereco.cidade}" size="60" />

						<p:outputLabel value="UF" for="uf" />
						<p:inputText id="uf" value="#{cadastroClienteBean.endereco.uf}"
							size="5" />
						<p:commandButton style="margin-top:20px"
							action="#{cadastroClienteBean.adicionarEndereco()}"
							value="Incluir" update="@form" process="@form" />

					</p:panelGrid>
				</h:panelGroup>
			</p:dialog>





			<p:dataTable id="enderecoTable" style="width: 100%; margin-top: 20px"
				emptyMessage="Nenhum endereço encontrado." rows="20" var="endereco"
				paginator="true" paginatorAlwaysVisible="false"
				value="#{cadastroClienteBean.cliente.enderecos}">

				<p:column headerText="Logradouro"
					style="text-align: center; width: 100px">
					<h:outputText value="#{endereco.logradouro}" />
				</p:column>

				<p:column headerText="Numero"
					style="text-align: center; width: 100px">
					<h:outputText value="#{endereco.numero}" />
				</p:column>


				<p:column headerText="Complemento"
					style="text-align: center; width: 100px">
					<h:outputText value="#{endereco.complemento}" />
				</p:column>


				<p:column headerText="CEP" style="text-align: center; width: 100px">
					<h:outputText value="#{endereco.cep}" />
				</p:column>


				<p:column headerText="Cidade/UF"
					style="text-align: center; width: 100px">
					<h:outputText value="#{endereco.cidade}" />
				</p:column>


				<p:column style="width: 100px; text-align: center">
					<p:commandButton icon="ui-icon-trash" title="Excluir"
						oncomplete="confirmacaoExclusaoEndereco.show();">
						<f:setPropertyActionListener value="#{endereco}"
							target="#{cadastroClienteBean.endereco}" />
					</p:commandButton>
				</p:column>
			</p:dataTable>

			<!--Dialog excluir Cliente-->

			<p:confirmDialog header="Exclusão de Cliente"
				message="Deseja realmente excluir?" widgetVar="confirmacaoExclusao">
				<p:button value="Não"
					onclick="confirmacaoExclusao.hide(); return false;" />
				<p:commandButton value="Sim"
					oncomplete="confirmacaoExclusao.hide();" />
			</p:confirmDialog>

			<p:confirmDialog header="Exclusão de Endereço"
				message="Deseja realmente excluir?"
				widgetVar="confirmacaoExclusaoEndereco">
				<p:button value="Não"
					onclick="confirmacaoExclusaoEndereco.hide(); return false;" />
				<p:commandButton value="Sim"
					oncomplete="confirmacaoExclusaoEndereco.hide();"
					action="#{cadastroClienteBean.removerEndereco()}" process="@this"
					update="@form">
				</p:commandButton>
			</p:confirmDialog>



		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/clientes/PesquisaClientes.xhtml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Pesquisa de clientes</ui:define>

	<ui:define name="corpo">
		<h:form id="frmPesquisa">
			<h1>Pesquisa de clientes</h1>

			<p:toolbar style="margin-top: 20px">
				<p:toolbarGroup>
					<p:commandButton value="Pesquisar"
						action="#{pesquisaClientesBean.pesquisar}" update="@form" />
				</p:toolbarGroup>
				<p:toolbarGroup align="right">
					<p:button value="Novo" outcome="/clientes/CadastroCliente" />
				</p:toolbarGroup>
			</p:toolbar>

			<p:panelGrid columns="2" id="painel"
				style="width: 100%; margin-top: 20px" columnClasses="rotulo, campo">


				<p:outputLabel value="Email" />
				<p:inputText size="40" value="#{pesquisaClientesBean.filtro.email}" />

				<p:outputLabel value="Nome" />
				<p:inputText size="40" value="#{pesquisaClientesBean.filtro.nome}" />


			</p:panelGrid>

			<p:dataTable id="clientesTable"
				value="#{pesquisaClientesBean.clientesFiltrados}" var="cliente"
				style="margin-top: 20px" emptyMessage="Nenhum cliente encontrado."
				rows="20" paginator="true" paginatorAlwaysVisible="false"
				paginatorPosition="bottom">

				<p:column headerText="Nome" style="width: 500px">
					<h:outputText value="#{cliente.nome}" />
				</p:column>

				<p:column headerText="Tipo" style="text-align: center; width: 190px">
					<h:outputText value="#{cliente.tipo}" />
				</p:column>

				<p:column headerText="CPF/CNPJ"
					style="text-align: center; width: 300px">
					<h:outputText value="#{cliente.documentoReceitaFederal}" />
				</p:column>

				<p:column headerText="Telefone"
					style="text-align: center; width: 300px">
					<h:outputText value="#{cliente.telefone}" />
				</p:column>

				<p:column style="width: 100px; text-align: center">
					<p:button outcome="/clientes/CadastroCliente" icon="ui-icon-pencil"
						title="Editar">
						<f:param name="cliente" value="#{cliente.id}" />
					</p:button>


					<p:commandButton icon="ui-icon-trash" title="Excluir"
						oncomplete="confirmacaoExclusao.show();" process="@this"
						update=":frmPesquisa:confirmacaoExclusaoDialog">
						<!-- Atribui o produto a ser excluido em uma variavel no Bean -->
						<f:setPropertyActionListener value="#{cliente}"
							target="#{pesquisaClientesBean.clienteSelecionado}" />
					</p:commandButton>
				</p:column>
			</p:dataTable>

			<p:confirmDialog header="Exclusão de Cliente"
				message="Deseja realmente excluir o cliente #{pesquisaClientesBean.clienteSelecionado.nome}?"
				widgetVar="confirmacaoExclusao" id="confirmacaoExclusaoDialog">
				<p:button value="Não"
					onclick="confirmacaoExclusao.hide(); return false;" />
				<p:commandButton value="Sim"
					oncomplete="confirmacaoExclusao.hide();"
					action="#{pesquisaClientesBean.excluir}" process="@this"
					update=":frmPesquisa:clientesTable" />
			</p:confirmDialog>

		</h:form>
	</ui:define>
</ui:composition>