src/main/java/com/algaworks/pedidovenda/model/ItemPedido.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "item_pedido")
public class ItemPedido implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Integer quantidade = 1;
	private BigDecimal valorUnitario = BigDecimal.ZERO;
	private BigDecimal valorCusto = BigDecimal.ZERO;
	private Produto produto;
	private Pedido pedido;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(nullable = false, length = 3)
	public Integer getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "valor_unitario", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@ManyToOne
	@JoinColumn(name = "pedido_id", nullable = false)
	public Pedido getPedido() {
		return pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "valor_custo", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorCusto() {
		return valorCusto;
	}

	public void setValorCusto(BigDecimal valorCusto) {
		this.valorCusto = valorCusto;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemPedido other = (ItemPedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorTotal() {
		return this.getValorUnitario().multiply(
				new BigDecimal(this.getQuantidade()));
	}

	@Transient
	public boolean isProdutoAssociado() {
		return this.getProduto() != null && this.getProduto().getId() != null;
	}

	@Transient
	public boolean isEstoqueSuficiente() {// O estoque é sufuciente?
		return this.getPedido().isEmitido() // Se foi emitido OU se estoque for
											// maior que quantidade do item
				|| this.getProduto().getId() == null
				|| this.getProduto().getQuantidadeEstoque() >= this
						.getQuantidade();
	}

	@Transient
	public boolean isEstoqueInsuficiente() {
		return !this.isEstoqueSuficiente(); // Retorna o contrario do
											// isEstoqueSuficiente
											// Nego
	}

}

src/main/java/com/algaworks/pedidovenda/model/Pedido.java
package com.algaworks.pedidovenda.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.inject.Inject;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

import com.algaworks.pedidovenda.service.CadastroPedidoService;
import com.algaworks.pedidovenda.service.ParcelamentoService;
import com.algaworks.pedidovenda.util.jpa.Transactional;

@Entity
@Table(name = "pedido")
public class Pedido implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;
	private Date dataCriacao;
	private String observacao;
	private BigDecimal valorDesconto = BigDecimal.ZERO;
	private BigDecimal valorTotal = BigDecimal.ZERO;
	private StatusPedido status = StatusPedido.ORCAMENTO;
	private FormaPagamento formaPagamento;
	private Usuario vendedor;
	private Cliente cliente;
	private Integer repetir;
	private List<ItemPedido> itens = new ArrayList<>();
	private List<Parcelamento> parcelamentos = new ArrayList<>();
	private Date dataQuita;

	@Id
	@GeneratedValue
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Transient
	public boolean isNovo() {
		return getId() == null;
	}

	@Transient
	public boolean isExistente() {
		return !isNovo();
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_criacao", nullable = false)
	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}

	@Column(columnDefinition = "text")
	public String getObservacao() {
		return observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@NotNull
	@Column(name = "valor_desconto", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorDesconto() {
		return valorDesconto;
	}

	public void setValorDesconto(BigDecimal valorDesconto) {
		this.valorDesconto = valorDesconto;
	}

	@NotNull
	@Column(name = "valor_total", nullable = false, precision = 10, scale = 2)
	public BigDecimal getValorTotal() {
		return valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 20)
	public StatusPedido getStatus() {
		return status;
	}

	public void setStatus(StatusPedido status) {
		this.status = status;
	}

	@NotNull
	@Enumerated(EnumType.STRING)
	@Column(name = "forma_pagamento", nullable = false, length = 20)
	public FormaPagamento getFormaPagamento() {
		return formaPagamento;
	}

	public void setFormaPagamento(FormaPagamento formaPagamento) {
		this.formaPagamento = formaPagamento;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "vendedor_id", nullable = false)
	public Usuario getVendedor() {
		return vendedor;
	}

	public void setVendedor(Usuario vendedor) {
		this.vendedor = vendedor;
	}

	@NotNull
	@ManyToOne
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	public List<ItemPedido> getItens() {
		return itens;
	}

	public void setItens(List<ItemPedido> itens) {
		this.itens = itens;
	}

	
	@Column(name = "repetir", nullable = true)
	public Integer getRepetir() {
		return repetir;
	}

	public void setRepetir(Integer repetir) {
		this.repetir = repetir;
	}

	@OneToMany(mappedBy = "pedido", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
	public List<Parcelamento> getParcelamentos() {
		return parcelamentos;
	}

	public void setParcelamentos(List<Parcelamento> parcelamentos) {
		this.parcelamentos = parcelamentos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", nullable = true)
	public Date getDataQuita() {
		return dataQuita;
	}

	public void setDataQuita(Date dataQuita) {
		this.dataQuita = dataQuita;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pedido other = (Pedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorSubtotal() {
		BigDecimal total = BigDecimal.ZERO;
		// somar itens do pedido
		for (ItemPedido item : this.getItens()) {// Soma os pedidos adicionados
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		return total;
	}

	@Transient
	public Integer getParcelas() {
		return this.getRepetir();
	}

	public void recalcularValorTotal() {
		BigDecimal total = BigDecimal.ZERO;

		total = total.subtract(this.getValorDesconto());

		// somar itens do pedido
		for (ItemPedido item : this.getItens()) {// Soma os pedidos adicionados
			if (item.getProduto() != null && item.getProduto().getId() != null) {
				total = total.add(item.getValorTotal());
			}
		}
		this.setValorTotal(total);
	}

	// Adiciona item vazio na capa de pedido dentro do item
	public void adicionarItemVazio() {
		if (this.isOrcamento()) { // Se for orçamento adiciona
			Produto produto = new Produto();

			ItemPedido item = new ItemPedido();
			item.setProduto(produto);
			item.setPedido(this);

			this.getItens().add(0, item);// Adiciona o item na posição zero,
											// sempre
		}

	}

	@Transient
	// Nao é mapeamento JPA (Get)
	public boolean isOrcamento() {
		return StatusPedido.ORCAMENTO.equals(this.getStatus());
	}

	public void removerItemVazio() {
		ItemPedido primeiroItem = this.getItens().get(0);

		if (primeiroItem != null && primeiroItem.getProduto().getId() == null) {
			this.getItens().remove(0);
		}

	}

	@Transient
	public Integer getNumParc() {
		return this.getRepetir();
	}

	@Transient
	public boolean isValorTotalNegativo() {
		return this.getValorTotal().compareTo(BigDecimal.ZERO) < 0;
	}

	@Transient
	public boolean isEmitido() {
		return StatusPedido.EMITIDO.equals(this.getStatus());
	}

	@Transient
	public boolean isPromissoria() {
		return FormaPagamento.PROMISSORIA.equals(this.getFormaPagamento());
	}

	@Transient
	public boolean isParcelavel() {
		return this.isPromissoria() || this.isCartaoCredito();
	}

	@Transient
	public boolean isCartaoCredito() {
		return FormaPagamento.CARTAO_CREDITO.equals(this.getFormaPagamento());
	}

	@Transient
	public boolean isNaoEmissivel() {
		return !this.isEmissivel();
	}

	@Transient
	public boolean isEmissivel() {
		return this.isExistente() && this.isOrcamento();
	}

	@Transient
	public boolean isNaoCancelavel() {
		return !isCancelavel();

	}

	@Transient
	public boolean isCancelavel() {
		return this.isExistente() && !this.isCancelado();
	}

	@Transient
	public boolean isQuitado() {
		return this.getDataQuita() != null;
	}

	@Transient
	public boolean isQuitadobotao() {
		return this.isOrcamento() || this.isQuitado();
	}

	@Transient
	private boolean isCancelado() {
		return StatusPedido.CANCELADO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoAlteravel() {
		return !isAlteravel();
	}

	@Transient
	private boolean isAlteravel() {
		return this.isOrcamento();
	}

	@Transient
	private boolean isCredito() {
		return FormaPagamento.CARTAO_CREDITO.equals(this.getStatus());
	}

	@Transient
	public boolean isNaoEnviavelPorEmail() {
		return this.isNovo() || this.isCancelado();
	}

	@Transient
	public boolean isNulo() {
		return this.getItens() != null;
	}

}

src/main/webapp/WEB-INF/template/pedidos/BotoesPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<p:toolbar style="margin-top: 20px">
  		<p:toolbarGroup>
  			<p:button value="Novo" outcome="/pedidos/CadastroPedido"/>
  			<p:commandButton value="Salvar" action="#{cadastroPedidoBean.salvar()}"
  				update="@form"  />
  		</p:toolbarGroup>
  		
  		<p:toolbarGroup align="right">
  		
  			<p:commandButton value="Emitir" action="#{emissaoPedidoBean.emitirPedido}"
  				process="@form" update="@form" disabled="#{cadastroPedidoBean.pedido.naoEmissivel}"/>
  			<p:commandButton value="Cancelar" action="#{cancelamentoPedidoBean.cancelarPedido}"
  			process="@this" update="@form" disabled="#{cadastroPedidoBean.pedido.naoCancelavel}"/>
  			<p:commandButton value="Enviar por e-mail" action="#{envioPedidoEmailBean.enviarPedido}"
  			process="@this" disabled="cadastroPedidoBean.pedido.naoEnviavelPorEmail	"/>
  			
  			<p:separator/>
  		
  			<p:button value="Pesquisa" outcome="/pedidos/PesquisaPedidos" />
  		</p:toolbarGroup>
  	</p:toolbar>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/CapaPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:panelGrid columns="4" style="width: 100%; margin-top: 20px"
		columnClasses="rotulo, campo, rotulo, campo">
		<p:outputLabel value="Número"
			rendered="#{cadastroPedidoBean.pedido.existente}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.id}"
			rendered="#{cadastroPedidoBean.pedido.existente}" />

		<p:outputLabel value="Data de criação"
			rendered="#{cadastroPedidoBean.pedido.existente}" />
		<h:outputText value="#{cadastroPedidoBean.pedido.dataCriacao}"
			rendered="#{cadastroPedidoBean.pedido.existente}">
			<f:convertDateTime pattern="dd/MM/yyyy" />
		</h:outputText>

		<p:outputLabel value="Status" />
		<h:outputText value="#{cadastroPedidoBean.pedido.status.descricao}" />

		<p:outputLabel value="Vendedor" for="vendedor" />
		<p:selectOneMenu id="vendedor"
			value="#{cadastroPedidoBean.pedido.vendedor}"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}">
			<f:selectItem itemLabel="Selecione" />
			<f:selectItems value="#{cadastroPedidoBean.vendedores}"
				var="vendedor" itemValue="#{vendedor}" itemLabel="#{vendedor.nome}" />
		</p:selectOneMenu>

		<p:outputLabel value="Cliente" for="cliente" />
		<p:autoComplete id="cliente" size="40" dropdown="true"
			value="#{cadastroPedidoBean.pedido.cliente}"
			completeMethod="#{cadastroPedidoBean.completarCliente}" var="cliente"
			itemLabel="#{cliente.nome}" itemValue="#{cliente}"
			forceSelection="true"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

		<p:outputLabel value="Forma de pagamento" for="formaPagamento" />
		<p:selectOneMenu id="formaPagamento"
			value="#{cadastroPedidoBean.pedido.formaPagamento}"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}">
			<f:selectItem itemLabel="Selecione" />
			<f:selectItems value="#{cadastroPedidoBean.formasPagamento}"
				var="formaPagamento" itemValue="#{formaPagamento}"
				itemLabel="#{formaPagamento.descricao}" />
		</p:selectOneMenu>



		<p:outputLabel value="Subtotal" style="font-weight: bold" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorSubtotal}"
			style="font-weight: bold" id="subtotal">


			<f:convertNumber type="currency" />
		</h:outputText>

		<p:outputLabel value="Valor de desconto" for="valorDesconto" />
		<p:inputText id="valorDesconto" size="10" maxlength="10"
			styleClass="moeda" value="#{cadastroPedidoBean.pedido.valorDesconto}"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}">
			<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />

			<p:ajax event="change" process="@this" update="totalPedido"
				listener="#{cadastroPedidoBean.recalcularPedido}" />

		</p:inputText>

		<p:outputLabel value="Total do pedido"
			style="font-weight: bold; font-size: 1.1em" />
		<h:outputText value="#{cadastroPedidoBean.pedido.valorTotal}"
			style="font-weight: bold; font-size: 1.1em" id="totalPedido">
			<f:convertNumber type="currency" />
		</h:outputText>
	</p:panelGrid>

</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/ItensPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:dataTable value="#{cadastroPedidoBean.pedido.itens}" var="item"
		id="tabelaItens" rowIndexVar="linha"> <!-- Armazena indice da linha -->
		<p:column headerText="SKU" style="text-align: center; width: 100px">
		
			<h:outputText value="#{item.produto.sku}" rendered="#{item.produtoAssociado}"/>
			
			<p:inputText size="8" value="#{cadastroPedidoBean.sku}" label="SKU"
			rendered="#{not item.produtoAssociado}">
				<p:ajax event="change" process="@this"
				update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
				listener="#{cadastroPedidoBean.carregarProdutoPorSku}"/>
			</p:inputText>
			
		</p:column>
		<p:column headerText="Produto">

		<h:outputText value="#{item.produto.nome}" rendered="#{item.produtoAssociado}" />
		
			<p:autoComplete styleClass="produto-tabela"
				value="#{cadastroPedidoBean.produtoLinhaEditavel}"
				completeMethod="#{cadastroPedidoBean.completarProduto}"
				var="produto" itemLabel="#{produto.nome}" itemValue="#{produto}"
				forceSelection="true" rendered="#{not item.produtoAssociado}">
				<!-- Renderiza quando nao tiver Prod -->
				<p:ajax event="itemSelect"
					update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
					listener="#{cadastroPedidoBean.carregarProdutoLinhaEditavel}" />
			</p:autoComplete>

		</p:column>
		<p:column headerText="Valor unitário"
			style="text-align: right; width: 120px">
			<h:outputText value="#{item.valorUnitario}">
				<f:convertNumber type="currency" />
			</h:outputText>
		</p:column>
		<p:column headerText="Quantidade"
			style="text-align: center; width: 100px">
			<p:inputText size="8" value="#{item.quantidade}" disabled="#{cadastroPedidoBean.pedido.naoAlteravel}"  >
				<p:ajax event="change" process="@this"
				update="tabelaItens :frmCadastro:totalPedido :frmCadastro:subtotal"
				listener="#{cadastroPedidoBean.atualizarQuantidade(item, linha)}"/> <!-- Alem do obj, passa
				o indice da linha como parametro -->
			</p:inputText>
		</p:column>
		
		<p:column headerText="Estoque" style="text-align: center; width: 100px">
			<h:outputText value="#{item.produto.quantidadeEstoque}" 
				style="#{item.estoqueInsuficiente ? 'color: red' : ''}"/>
			
			<h:graphicImage library="images" name="alerta.png" id="semEstoque"
				style="vertical-align: bottom; margin-left: 5px" 
				rendered="#{item.estoqueInsuficiente}" />
				
			<p:tooltip for="semEstoque" value="Estoque insuficiente"
				rendered="#{item.estoqueInsuficiente}" />
		</p:column>
		
		
		
		
		<p:column headerText="Valor total"
			style="text-align: right; width: 100px">
			<h:outputText value="#{item.valorTotal}">
				<f:convertNumber type="currency" />
			</h:outputText>
		</p:column>

		<p:columnGroup type="footer">
			<p:row>
				<p:column colspan="5" footerText="Subtotal"
					style="text-align: right" />
				<p:column footerText="#{cadastroPedidoBean.pedido.valorSubtotal}" style="text-align: right" />
			</p:row>
		</p:columnGroup>
	</p:dataTable>


</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/ObservacaoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	<h:panelGroup layout="block" style="padding-right: 10px">
		<p:inputTextarea rows="10" style="width: 100%" value="#{cadastroPedidoBean.pedido.observacao}"
		  />
	</h:panelGroup>
  	
</ui:composition>

src/main/webapp/WEB-INF/template/pedidos/ParcelamentoPedido.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui">


	<p:panelGrid id="pnlParc" columns="6" columnClasses="rotulo, campo">
		<p:outputLabel value="Parcelas" for="parc" />
		<p:inputText id="parc" size="8" maxlength="80"
			value="#{cadastroPedidoBean.pedido.repetir}"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}">
		</p:inputText>

		<p:commandButton style="margin-top:2px"
			action="#{cadastroPedidoBean.calculaParcelas()}" value="Calcular"
			update="tabelaParc" process="@form"
			disabled="#{cadastroPedidoBean.pedido.naoAlteravel}" />

		<p:commandButton value="Quitar Parcelas"
			oncomplete="confirmacaoQuitar.show();" process="@this"
			update="tabelaParc" style="margin-top:2px"
			disabled="#{cadastroPedidoBean.pedido.quitadobotao}"
			  />
			
		<p:outputLabel value="Pagamento quitado em:" rendered="#{cadastroPedidoBean.pedido.quitado}"/>
		<h:outputText value="#{cadastroPedidoBean.pedido.dataQuita}">
			<f:convertDateTime pattern="dd/MM/yyyy" />
		</h:outputText>
	</p:panelGrid>

	<p:dataTable id="tabelaParc" rowIndexVar="linhaParc" editable="true"
		style="width: 100%; margin-top: 20px" editMode="cell"
		value="#{cadastroPedidoBean.pedido.parcelamentos}" var="itemParcela">

		<p:ajax event="cellEdit" listener="#{cadastroPedidoBean.onCellEdit}"
			update="@this" />

		<f:facet name="header">
           Parcelas
       </f:facet>
		<p:column headerText="Numero Parcela"
			style="text-align: center; width: 50px">
			<h:outputText size="8" value="#{itemParcela.num_parc}">
			</h:outputText>
		</p:column>

		<p:column headerText="Data Pagamento"
			style="text-align: center; width: 100px">
			<h:outputText value="#{itemParcela.date}">
				<f:convertDateTime pattern="dd/MM/yyyy" />
			</h:outputText>
		</p:column>

		<p:column headerText="Status" style="text-align: center; width: 100px">
			<h:outputText value="#{itemParcela.pagamento.descricao}">
			</h:outputText>
		</p:column>

		<p:column headerText="Valor Parcela"
			style="text-align: center; width: 20px">
			<h:outputText value="#{itemParcela.valores}"
				style="margin-right:15px">
			</h:outputText>
		</p:column>

		<p:column headerText="Status Alterar"
			style="text-align: center; width: 20px">
			<p:cellEditor>
				<f:facet name="output">
					<h:outputText value="#{itemParcela.pagamento.descricao}" />
				</f:facet>
				<f:facet name="input">
					<h:selectOneMenu value="#{itemParcela.pagamento}"
						style="width:100%">
						<f:selectItems value="#{cadastroPedidoBean.estadoPagamento}"
							var="man" itemLabel="#{man.descricao}" itemValue="#{man}" />
					</h:selectOneMenu>
				</f:facet>
			</p:cellEditor>
		</p:column>
	</p:dataTable>



	<p:confirmDialog header="Quitar Parcelas"
		message="Deseja realmente quitar todas as parcelas?"
		widgetVar="confirmacaoQuitar" id="confirmacaoQuitarDialog">
		<p:button value="Não"
			onclick="confirmacaoQuitar.hide(); return false;" />
		<p:commandButton value="Sim" oncomplete="confirmacaoQuitar.hide();"
			action="#{cadastroPedidoBean.quitarPedido()}" process="@this"
			update="pnlParc tabelaParc" />
	</p:confirmDialog>

</ui:composition>